server:
  servlet:
    context-path: /easyui

mybatis:
  type-aliases-package: com.cssl.pojo
  mapper-locations: classpath:com/cssl/dao/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  page-size-zero: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///msg
    username: root
    password: 123

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8


